//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuthAPI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOAuthService")]
    public interface IOAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOAuthService/Login", ReplyAction="http://tempuri.org/IOAuthService/LoginResponse")]
        string Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOAuthService/Login", ReplyAction="http://tempuri.org/IOAuthService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOAuthService/Register", ReplyAction="http://tempuri.org/IOAuthService/RegisterResponse")]
        string Register(string name, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOAuthService/Register", ReplyAction="http://tempuri.org/IOAuthService/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string name, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOAuthService/ChangePassword", ReplyAction="http://tempuri.org/IOAuthService/ChangePasswordResponse")]
        string ChangePassword(string username, string password, string confirmpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOAuthService/ChangePassword", ReplyAction="http://tempuri.org/IOAuthService/ChangePasswordResponse")]
        System.Threading.Tasks.Task<string> ChangePasswordAsync(string username, string password, string confirmpassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOAuthServiceChannel : OAuthAPI.ServiceReference1.IOAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OAuthServiceClient : System.ServiceModel.ClientBase<OAuthAPI.ServiceReference1.IOAuthService>, OAuthAPI.ServiceReference1.IOAuthService {
        
        public OAuthServiceClient() {
        }
        
        public OAuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OAuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OAuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OAuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public string Register(string name, string username, string password) {
            return base.Channel.Register(name, username, password);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string name, string username, string password) {
            return base.Channel.RegisterAsync(name, username, password);
        }
        
        public string ChangePassword(string username, string password, string confirmpassword) {
            return base.Channel.ChangePassword(username, password, confirmpassword);
        }
        
        public System.Threading.Tasks.Task<string> ChangePasswordAsync(string username, string password, string confirmpassword) {
            return base.Channel.ChangePasswordAsync(username, password, confirmpassword);
        }
    }
}
